export const PLACEMENT_SUMMARY_LINKS = {
  '2024-25': {
    href: 'https://drive.google.com/file/d/1CcgWUPgPEmzXW5OgmP2AwYZntxwY-gju/view?usp=sharing',
    label: 'College Placement Summary 2024-25',
  },
  2023: {
    href: 'https://drive.google.com/file/d/1t-P-mjTQzrJzB6D2TeHA5Z4qtrZT8vBQ/view?usp=sharing',
    label: 'College Placement Summary 2023',
  },
}

export const PLACEMENT_BATCHES = [
  {
    year: '2024-25',
    cohort: '104',
    summaryKey: '2024-25',
    columns: [
      {
        name: 'India',
        colleges: [
          'Amity University',
          'Aryabhatta College, DU',
          'Ashoka University',
          'Deen Dayal College, DU',
          'Deshbandhu College, DU',
          'FLAME University',
          'Galgotias university',
          'Global Music Institute',
          'The Indian Institute of Management - Kozhikode, Kerela',
          'Institute of Integrated Learning in Management. Gurgoan (IILM)',
          'Kamla Nehru College, DU',
          'KREA University',
          'Lady Irwin College, DU',
          'Lakshmibai College, DU',
          'Manav Rachna University',
          'Narsee Monjee Instititute of Management',
          'National Law University - Banglore',
          'O.P. Jindal Global University',
          'Plaksha University',
          'Ramanujan College, DU',
          'SGT University',
          'Shiv Nadar University',
          'Shri Ram College of Commerce, DU',
          'Srishti School of Design',
          'Sri Venkastewara College, DU',
          'SRM Medical College',
          'S.R.M University',
          'Symbiosis University',
          'Thapar Institute of Engineering and Technology',
          'Vivekananda Institute of Professional Studies (VIPS)',
        ],
      },
      {
        name: 'USA',
        colleges: [
          'Barnard College',
          'Boston University',
          'Brown University',
          'Dartmouth College',
          'Emerson College',
          'George Washington University',
          'Harvard University',
          'Northeastern University',
          'Northwestern University',
          'Parsons School of Design at The New School',
          'Pratt Institute',
          'Purdue University',
          'Rochester Institute of Technology',
          'Smith College',
          'Stanford University',
          'Swarthmore College',
          'Tufts University',
          'University of California, Los Angeles',
          'University of Southern California',
          'University of California, San Diego',
          'University of Virginia',
          'Vanderbilt University',
          'Wesleyan University',
        ],
      },
      {
        name: 'UK',
        colleges: [
          'Durham University',
          'Imperial College London',
          'Istituto Marangoni',
          "King's College London",
          'London School of Economics',
          'Queen Mary University of London',
          'University of the Arts London',
          'University College London',
          'University of Edinburgh',
          'University of St Andrews',
          'University of Warwick',
        ],
      },
      {
        name: 'Others',
        colleges: [
          'Lasalle College of Arts, Singapore',
          'Istituto Marangoni, Milan',
          'New York University, Abu Dhabi',
          'University College Dublin, Ireland',
          'University of Europe for applied sciences, Berlin',
          'University of Sydney, Australia',
        ],
      },
    ],
  },
  {
    year: '2023-24',
    cohort: '95',
    columns: [
      {
        name: 'India',
        colleges: [
          'Amity University',
          'Ashoka University',
          'Azim Premji University, Bangalore',
          'Delhi Technological University',
          'IILM-Gurgaon',
          'Indian Institute of Art and Design',
          'Indian Institute of Technology- Madras',
          'ITC Maurya Hotel',
          'Maitreyi College, Delhi University',
          'Miranda House, Delhi University',
          'National Institute of Fashion Technology, Delhi',
          'National Institute of Fashion Technology, Kangra',
          'National Law School, Jodhpur',
          'NIIT University',
          'O.P. Jindal Global University',
          'Plaksha University, Mohali',
          'Ramanujan College, Delhi University',
          'Shiv Nadar University',
          'SRM University',
          'Sriram Bhartiya Kala Kendra + IGNOU',
          'Sushant University',
          'Thapar Institute of Engineering and Technology',
        ],
      },
      {
        name: 'USA',
        colleges: [
          'Babson College',
          'Barnard College',
          'Bentley University',
          'Boston University',
          'Bryant University',
          'Carnegie Mellon University',
          'Colby University',
          'Colgate University',
          'Dartmouth College',
          'Emory University',
          'Georgetown University',
          'Indiana University, Bloomington',
          'Johns Hopkins University',
          'Loyola Marymount University',
          'New York University',
          'Northeastern University',
          'Purdue University',
          'Rhode Island School of Design',
          'Santa Clara University',
          'Tulane University',
          'University of California Irvine',
          'University of California, Santa Barbara',
          'University of Chicago',
          'University of Illinois, Urbana Champaign',
          'University of Massachusetts, Amherst',
          'University of Miami',
          'University of Pennsylvania',
          'University of Southern California',
          'University of Virginia',
          'Wesleyan University',
        ],
      },
      {
        name: 'UK',
        colleges: [
          'Durham University',
          'Regents University',
          'University of Arts London',
          'University of Bath',
          'University of Manchester',
          'University of Edinburgh',
          'University of Glasgow',
          'University of St. Andrews',
          'University of Warwick',
          'University of York',
        ],
      },
      {
        name: 'Canada',
        colleges: ['University of British Columbia'],
      },
      {
        name: 'Other Countries',
        colleges: [
          'Istituto Marangoni Dubai',
          'Monash University',
          'University of Melbourne',
        ],
      },
    ],
  },
  {
    year: '2023',
    cohort: '84',
    summaryKey: '2023',
    columns: [
      {
        name: 'India',
        colleges: [
          'Amity University',
          'Ashoka University',
          'Atma Ram Sanatan Dharma College, University of Delhi',
          'Azim Premji University, Bangalore',
          'Maharaja Agrasen College, Indraprastha University',
          'BA School of Open Learning, Delhi University',
          'Bennett University',
          'Birla Institute of Technology and Science-Pilani',
          'Delhi Skill and Entrepreneurship University-Delhi',
          'Delhi Technological University',
          'Dronacharya College of Engineering',
          'Flame University',
          'Indian Institute of Technology- Varanasi',
          'Indian School of Hospitality, Gurugram',
          'Indraprastha Institute of Information Technology, Delhi',
          'ITC Maurya Hotel',
          'Jesus and Mary College, University of Delhi',
          'Kalinga Institute of Industrial Technology - Bhubaneshwar',
          'Khalsa College, University of Delhi',
          'KREA University',
          'Manipal Institute of Technology ,Manipal',
          'Mahatma Gandhi Medical College and Research Institute, Pondicherry',
          'Meerabai Institute of Technology Maharani Bagh Campus',
          'Narsee Monjee Institute of Management Studies',
          'O.P. Jindal Global University',
          'Plaksha University ,Mohali',
          'S.P Jain School of Management, Mumbai',
          'Sri Venkateswara College, University of Delhi',
          "St Stephen's College, University of Delhi",
          'Sushant University',
          'University of Petroleum and Energy Studies -Dehradun',
          'Vellore Institute of Technology - Bhopal',
          'Vellore Institute of Technology, Vellore',
        ],
      },
      {
        name: 'USA',
        colleges: [
          'Barnard College',
          'Bryant University',
          'Emory University',
          'Illinois Institute of Technology -Chicago',
          'Indiana University',
          'Parsons School of Design',
          'Rhode Island School of Design',
          'Tulane University',
          'University of California -Los Angeles',
          'University of California-Santa Barbara',
          'University of Illinois-Urbana Champaign',
          'University of Southern California',
          'Yale University',
        ],
      },
      {
        name: 'UK',
        colleges: [
          'Cardiff University',
          'Kings College London',
          'London School of Economics and Political Science',
          'Regents University',
          'University of Arts London',
          'University of Bath',
          'University of Brighton',
          'University of Edinburgh',
          'University of Oxford',
          'University of St. Andrews',
          'University of Warwick',
        ],
      },
      {
        name: 'Canada',
        colleges: [
          'Emily Carr University',
          'McGill University',
          'University of British Columbia',
          'University of Waterloo',
        ],
      },
      {
        name: 'Others',
        colleges: [
          'Istituto Marangoni Milan',
          'University College Utrecht',
          'Vilnius University in Lithuania',
        ],
      },
    ],
  },
  {
    year: '2022',
    cohort: '86',
    columns: [
      {
        name: 'India',
        colleges: [
          'Amity University',
          'Ashoka University',
          'Flame University',
          'Global Music School',
          'The IIT Bombay Industrial Design Centre School of Design',
          'Indian Institute of Technology IIT- Kanpur',
          'Indian school of Design',
          'Indian School of Hospitality',
          'Jesus and Mary College',
          'Manav Rachna University',
          'National Institute of Fashion Technology-Bangalore, Delhi',
          'National Law University- Bhopal',
          'OP Jindal University',
          'Pearl Academy',
          "St. Xavier's College",
        ],
      },
      {
        name: 'USA',
        colleges: [
          'Babson College',
          'Boston University',
          'Claremont Mckenna College',
          'Cornell University',
          'Dartmouth University',
          'Emory University',
          'George Washington University',
          'Georgetown University',
          'Harvey Mudd College',
          'Indiana University',
          'Northeastern University',
          'Parsons School of Design',
          'Pratt Institute',
          'Princeton University',
          'Stanford University',
          'Tulane University',
          'University of California, San Diego',
          'University of California, Los Angeles',
          'University of California, Santa Barbara',
          'University of Illinois- Urbana Champaign',
          'University of Southern California',
          'University of Massachusetts Amherst',
          'University of Wisconsin Madison',
          'Wakeforest University',
          'Wesleyan University',
        ],
      },
      {
        name: 'UK',
        colleges: [
          'Bath University',
          'Kings College London',
          'London School of Economics',
          'St. Andrews University',
          'University of Arts- Central Saint Martins',
          'University of Birkbeck',
          'Warwick University',
          'Westminster University',
        ],
      },
      {
        name: 'Canada',
        colleges: [
          'University of British Columbia',
          'University of Toronto',
          'University of Victoria',
          'University of Waterloo',
          'York University',
        ],
      },
      {
        name: 'Others',
        colleges: [
          'Trinity College Dublin',
          'Erasmus University- Rotterdam',
          'University of Amsterdam',
          'Lasalle- University of Creative Arts',
        ],
      },
    ],
  },
  {
    year: '2021',
    cohort: '93',
    columns: [
      {
        name: 'India',
        colleges: [
          'Ashoka University',
          'Flame University, Pune',
          'Institute of Integrated Learning in Management',
          'Jesus and Mary College',
          'Khalsa College',
          'Lady Shri Ram College',
          'Maitreyi College, Delhi University',
          'Manipal Institute of Communication',
          'O.P Jindal University',
          "People's Education Society University",
          'Ramjas College, Delhi University',
          'Shri Ram College of Commerce',
          'Srishti School of Design and Technology',
          "St Stephen's College",
          "St. Xavier's College , Kolkata",
          'Symbiosis, Pune',
          'Venkateswara College',
        ],
      },
      {
        name: 'USA',
        colleges: [
          'Carnegie Mellon University',
          'Bard College',
          'Barnard College',
          'Berklee College of Music',
          'Brown University',
          'Chapman University',
          'Claremont McKenna College',
          'Georgia Institute of Technology',
          'New York University',
          'Northeastern University',
          'Pepperdine University',
          'Pomona College, California',
          'Skidmore College',
          'Smith College',
          'The New School-Parsons',
          'University of California - San Diego',
          'University of California- Los Angels',
          'University of Illinois, Urbana Champagne',
          'University of Michigan - Ann Arbor',
          'Wellesley College',
        ],
      },
      {
        name: 'UK',
        colleges: [
          'Durham University',
          'Kings College London',
          'London School of Economics',
          'London School of Economics',
          'Northrumbia University, Newcastle',
          'University of Edinburgh',
          'University of Manchester',
          'University of St Andrews',
          'University of Warwick',
        ],
      },
      {
        name: 'Canada',
        colleges: [
          'University of Toronto',
          'University of British Columbia',
          'University of Waterloo',
          'Wilfrid Laurier University',
        ],
      },
      {
        name: 'Others',
        colleges: [
          'Dubai Centre for Special Needs',
          'Ecole hoteliere de Lausanne',
          'Les Roches',
          'Singapore Management University',
          'Yale-NUS College',
        ],
      },
    ],
  },
  {
    year: '2020',
    cohort: '87',
    columns: [
      {
        name: 'India',
        colleges: [
          'Ashoka University',
          'Birla Institute of Technology & Science, Pilani',
          'Delhi Technological University',
          'Jesus and Mary College',
          'Lady Shri Ram College',
          'National Institute of Design, Kurukshetra',
          'O.P. Jindal University',
          'Pearl Academy',
          'Shri Ram College of Commerce',
          'Srishti Manipal Institute of Art, Design and Technology',
          "St. Stephen's College",
          'Vardhman Mahavir Medical College',
          'Vellore Institute of Technology',
        ],
      },
      {
        name: 'USA',
        colleges: [
          'Barnard College of Columbia University',
          'Bryant University',
          'Carnegie Mellon University',
          'Cornell University',
          'New York University',
          'Northwestern University',
          'Parsons School of Design',
          'Rhode Island School of Design',
          'Tufts University',
          'University of California, Berkeley',
          'University of California, Los Angeles',
          'University of California, San Diego',
          'University of Illinois at Urbana-Champaign',
          'University of Rochester',
        ],
      },
      {
        name: 'UK',
        colleges: [
          'Durham University',
          'Imperial College London',
          'London School of Economics',
          'Queen Mary University, London',
          'University College London',
          'University of Arts London',
          'University of St Andrews',
        ],
      },
      {
        name: 'Canada',
        colleges: [
          'University of British Columbia',
          'University of Toronto',
          'University of Waterloo',
        ],
      },
      {
        name: 'Others',
        colleges: ['Nanyang Technological University'],
      },
    ],
  },
  {
    year: '2019',
    cohort: '90',
    columns: [
      {
        name: 'India',
        colleges: [
          'Ashoka University',
          'Birla Institute of Technology & Science, Pilani',
          'Birla Institute of Technology & Science, Pilani',
          'Delhi Technological University',
          'Hansraj College',
          'Indraprastha College',
          'Jesus and Mary College',
          'Jesus and Mary College',
          'Lady Shri Ram College',
          'Maitreyi College',
          'National Law University, Kolkata',
          'O.P Jindal University',
          'Pearl Institute of Fashion',
          'Shaheed Bhagat Singh College',
          'St. Stephens College',
        ],
      },
      {
        name: 'USA',
        colleges: [
          'Babson University',
          'Boston University',
          'Cornell University',
          'Dartmouth College',
          'Emory University',
          'New York University',
          'Northwestern University',
          'Parsons New School',
          'University of Arizona',
          'University of California Berkeley',
          'University of Illinois, Urbana Champagne',
          'University of Michigan, Ann Arbour',
          'University of Pennsylvania',
          'University of Southern California',
          'Vanderbilt University',
        ],
      },
      {
        name: 'UK',
        colleges: [
          'Arts University, Bournemouth',
          'Kings College London',
          'Royal Holloway, London',
          'University College London',
          'University of Arts London',
          'University of Central Lancashire Medical College',
          'University of Creative Arts, London',
          'Warwick University',
        ],
      },
      {
        name: 'Canada',
        colleges: [
          'Alberta University',
          'McMaster University',
          'University of British Columbia',
          'University of Toronto',
        ],
      },
      {
        name: 'Others',
        colleges: [
          'Blue Mountain University Australia',
          'Ecole hoteliere de Lausanne, Hospitality',
          'ESSEC Business School',
          'European Business School',
          'Germany International College',
          'Glion Hospitality School',
          'Le Roche, Switzerland',
          'Nanyang Technological University',
          'Singapore Institute of Management',
          'Singapore Management University',
          'Trinity College',
        ],
      },
    ],
  },
  {
    year: '2018',
    cohort: '90',
    columns: [
      {
        name: 'India',
        colleges: [
          'Ambedkar University',
          'Ashoka University',
          'Avantika School of Design, Ujjain',
          'D.Y. Patil Medical College',
          'Delhi Technological University',
          'FLAME University',
          'Guru Gobind Singh Indraprastha University',
          'Hansraj College',
          'IIIT Hyderabad',
          'Institute of Hotel Management',
          'Jesus and Mary College',
          'Kamla Nehru College',
          'Maitreyi College',
          'Manipal University',
          'Miranda House',
          'Narsee Monjee College of Commerce and Economics',
          'National Institute of Fashion Technology',
          'NIIT University',
          'OP Jindal University',
          "St. Xavier's College, Mumbai",
          'West Bengal National University of Juridical Sciences',
        ],
      },
      {
        name: 'USA',
        colleges: [
          'Boston University',
          'Brown University',
          'California Institute of the Arts, School of Visual Arts',
          'Carnegie Mellon University- School of Computer',
          'Claremont McKenna College',
          'Cornell University',
          'Emory University',
          'Georgetown University',
          'Georgia Institute of Technology',
          'Miami University',
          'Northwestern University',
          'Parsons School of Design',
          'Purdue University',
          'Skidmore College',
          'The George Washington University',
          'Tufts University',
          'University of California, Los Angeles',
          'University of Pennsylvania',
          'University of Southern California',
          'Vanderbilt University',
          'Vassar College',
        ],
      },
      {
        name: 'UK',
        colleges: [
          'Bath School of Art and Design',
          'Bristol University',
          'Durham University',
          'Queen Mary University of London',
          'University of St Andrews',
          'Warwick University',
        ],
      },
      {
        name: 'Canada',
        colleges: [
          'McGill University',
          'McMaster University, Business School',
          'Rotman School of Commerce',
          'University of Alberta',
          'University of British Columbia',
          'University of Toronto',
          'University of Waterloo',
        ],
      },
      {
        name: 'Others',
        colleges: [
          'Hong Kong University of Science and Technology',
          'Nanyang Technological University',
          'Singapore Institute of Management',
        ],
      },
    ],
  },
]
